#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCHMNryy4BSaIMLNdljK0jUcPNRNsgBvOnKXW8I90bQRL6YXK5lRjGAsdIvWBqlOHR+ISrucrzsdrU9K3AuA1sImwHi8UAEALFDikPjF+BZvVG0tvUTkW3L4kQQo2Nd7HeJq5oxcQQUI6vUsbrKvpcS0Ee9xOyGZ/WRne9+AxN3qsbiyQaf2a18cpA/hu7+031/kyNItXFBl+9gm+Rbq6pDNL0olI+HyohPygryNMAQtdJQLm3IEGlZdoENVcq5CgRPFu99+0Z/uVsi39NEjfHD36bDimPSVvMxZKc6ns0AnsGU9tJ0REokpvdvlxW4DP2Cgpc83tCy0UUiCAZWMi7b aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
    ssh_pwauth: false
    disable_root: false

package_update: true
packages:
  - apache2
  - curl
  - wget
  - php
  - libapache2-mod-php
  - php-mysql
  - adminer

runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2

write_files:
  - content: |
      <?php
      $servername = "172.31.22.41";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";
      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
      }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while ($row = $result->fetch_assoc()) {
        echo ($row["Host"] . " / " . $row["User"] . "<br />");
      }
    path: /var/www/html/db.php
    permissions: "0644"
    owner: root:root

  - content: |
      <?php
      phpinfo();
    path: /var/www/html/info.php
    permissions: "0644"
    owner: root:root
